# Dockerfile.react

# ---- Build Stage ----
FROM node:20 AS build

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client/ .
RUN npm run build

# ---- Serve Stage ----
FROM nginx:alpine AS production

# Copy built files from React build stage
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
